apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      drink: tea
  template:
    metadata:
      labels:
        drink: tea
    spec:
      containers:
      - name: myappc
        image: httpd
        ports:
        - containerPort: 80
