apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypo
  name: mypo
spec:
  containers:
  - image: aakashgaur57/akapache1
    name: mypo
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
